name: testovoecz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.8
  provider: ^6.0.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.18




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#1463f5"
  image: assets/splash.png

flutter:


  uses-material-design: true

  assets:

    - assets/images/

